version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - nginx_cache:/tmp/nginx_cache
    depends_on:
      php:
        condition: service_healthy
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - SSL_EMAIL=admin@pulse_rowing_base.ru
      - DOMAIN=pulse_rowing_base.ru
    networks:
      - app-network

  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./scripts:/var/www/html/scripts
      - ./logs/php:/var/log/php
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    working_dir: /var/www/html
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pulse_rowing_db
      - DB_USER=pulse_user
      - DB_PASSWORD=pulse_password
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pulse_rowing_db
      - POSTGRES_USER=pulse_user
      - POSTGRES_PASSWORD=pulse_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pulse_user -d pulse_rowing_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "0.0.0.0:5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pulse.ru
      PGADMIN_DEFAULT_PASSWORD: admin_password
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  cron-auto-close:
    build:
      context: ./images/cron
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./scripts:/var/www/html/scripts
      - ./logs/cron:/var/log/cron
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=pulse_rowing_db
      - DB_USER=pulse_user
      - DB_PASSWORD=pulse_password

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin:
  nginx_cache: 